### ISSUE TITLE
lnd open channel error: expected funding_txid_str, got funding_txid_bytes

### ISSUE THREAD

**Issue by asoltys** [chill117/lnurl-node#15]
I'm trying to fulfill an openChannel request with lnd and it looks like lnurl-node expects to get back an object with "funding_txid_str" and "output_index" but I'm getting back "funding_txid_bytes" instead:

{
  funding_txid_bytes: 'ZWfJcPATOwRKugph5xzjIFVGt4z+WC6sxaxxaazjf2g=',
  output_index: 0
}

This is with lnd v0.10.1

I tried going back to lnd v0.9.0 to see if maybe the output had changed recently but still got bytes on that version (and no output_index).

**Comment by chill117** [comment]
Done. Will be included in next release.
