### ISSUE TITLE
“uses” with signed URLs?

### ISSUE THREAD

**Issue by cbetz** [chill117/lnurl-node#26]
I noticed before the "uses" concept was introduced a signed url could only be used once. I recently upgraded and now it appears signed urls (in my case withdrawals) can be used an unlimited number of times. Is it possible to specify "uses" for signed urls? 

BTW thank you for creating this awesome project 😀

**Comment by cbetz** [comment]
One thing to (selfishly) add: my use case just needs signed urls to default to 1 "uses" not unlimited. Could also specify a "uses" option when starting up the lnurl server.

**Comment by cbetz** [comment]
I just checked the sqlite db and it looks like the multiple withdraw requests are getting inserted with the same hash (see screenshot). Maybe this is related? 
<img width="1322" alt="Untitled" src="https://user-images.githubusercontent.com/458549/96350791-7126e000-1085-11eb-9316-494edb605b10.png">

**Comment by chill117** [comment]
The default number of uses is 1 - to maintain the previous behavior. So yes, it appears that the lack of unique constraint in SQLite seems to be the issue for you.

**Comment by chill117** [comment]
Fixed by https://github.com/chill117/lnurl-node/commit/fcf80ad5f3bbf592d312208220d26836f830c892

> The unique constraint on the hash column (defined in the urls table initialization) was being dropped (or ignored) by knex during each table alteration. A new migration to be run only if using SQLite3 will ensure the unique constraint is redefined after all migrations have run.

I almost feel like this is a bug in knex.

**Comment by chill117** [comment]
I added another test for checking the one-time-use only of signed URLs along with a few more safety checks to be extra certain that only one URL is saved to the data store.

The fixes will be included in the next release.

**Comment by cbetz** [comment]
Awesome, thank you!

**Comment by chill117** [comment]
Latest release (0.11.0) has the fix.
