### ISSUE TITLE
Host & Port for production server. 

### ISSUE THREAD

**Issue by chungquantin** [chill117/lnurl-node#35]
Hi @chill117, when I tried to host my server on production, the host and port (removed or not) will be localhost. Therefore, my lnurl server does not run on production (local development works fine).
```
// The host for the web server:
host: 'localhost',
// The port for the web server:
port: 3000,
// The protocol to use for the web server:
protocol: 'http',
```

**Comment by chill117** [comment]
How are you running the server? CLI or API? And how are you providing the configuration options?

**Comment by chungquantin** [comment]
I use API to create the server. Here is my configuration file
```
{
	"host":"localhost",
	"port":8080,
	"protocol":"http",
	"url": "My heroku server url",
	"endpoint": "/lnurl-server",
	"lightning": {
		"backend": "lnd",
		"config": {
			"hostname": "XXX",
			"cert": "XXX",
			"macaroon": "XXX"
		}
	},
	"store":{
		"backend": "knex",
		"config": {
			"client": "mysql",
			"connection": {
				"host": "XXX",
				"user": "XXX",
				"password": "XXX",
				"database": "XXX",
				"port": 3306
			}
		}
	}
}

```

**Comment by chungquantin** [comment]
When checking the heroku logs on production shell, it throws this 
`2021-07-07T12:37:45.355460+00:00 app[web.1]: Lnurl server listening at http://localhost:8080`
So I wonder lnurl server is hosted or not

**Comment by chill117** [comment]
Looks like it's working as expected. Are you trying to reach the lnurl-server from the public internet? It's recommended to run it behind an nginx (or other) reverse-proxy to handle TLS-termination at the host machine.

**Comment by chungquantin** [comment]
Ok thank you so much, I will try. I build this for my company based on your lnurl-toolbox, it's a very cool project!

**Comment by chungquantin** [comment]
@chill117 It seems doesn't work. Can I see your config for the production server?

**Comment by chill117** [comment]
I use a combination of docker and nginx to run lnurl servers in production. So I don't think it would help much for your situation. But you can have a look at the bleskomat-server project - it has example docker-compose files:

https://github.com/samotari/bleskomat-server

I suspect this is a networking issue in your Heroku setup.

What happens when you open a browser and type the host machine's IP address? Are you able to reach it?

**Comment by prusnak** [comment]
This is what I have in my config:

```
  "protocol": "http",
  "host": "0.0.0.0",
  "port": "3000",
  "url": "http://mydomain:3000",
   "endpoint": "/lnurl",
```

Afterwards the `http://mydomain:3000/lnurl` should work

**Comment by chungquantin** [comment]
@chill117 Thank you, I will take a look!
@prusnak Which domain do you use? Seems like Heroku does not allow sub domain
