### ISSUE TITLE
Add new LN backend: c-lightning

### ISSUE THREAD

**Issue by chill117** [chill117/lnurl-node#44]
There are a couple possible integrations w/ c-lightning:
* [ ] JSON-RPC via unix sock
* [ ] Sparko plug-in - provides an HTTP API

**Comment by PatrickGeyer** [comment]
Any progress on this @chill117?

**Comment by chill117** [comment]
@PatrickGeyer It's not currently a priority. But if you would like to give it a try, please feel free to do so. Pull-requests are welcome.

**Comment by chill117** [comment]
Moved this issue to the upstream dependency [lightning-backends-node](https://github.com/bleskomat/lightning-backends-node/issues/1)

**Comment by chill117** [comment]
@PatrickGeyer The latest release supports C-Lightning via its JSON-RPC unix sock or the HTTP-RPC API provided by the Sparko plugin.
