### ISSUE TITLE
LndBackend should not require cert

### ISSUE THREAD

**Issue by brh28** [chill117/lnurl-node#58]
I'm using an LND backend connected to a Voltage server, which does not require providing a cert. Unfortunately, I'm currently getting an error at startup saying the `lightning.config.cert` is a required field. 

Looking at the LndBackend (lib/lightning/lnd.js) class in my node_modules, I see the cert is listed as a required field, but when I check a similar [file](https://github.com/bleskomat/lightning-backends-node/blob/master/lib/backends/lnd.js) in the underlying lightning-backends-node, it looks like it's configured correctly, implying that I'm pulling a different class somehow.

I'm wondering where the LndBackend is pulled from and how it can be replaced.

**Comment by chill117** [comment]
It is necessary to provide a TLS certificate to securely connect to your LND node. Without the certificate, the connection could be MITM'ed and your macaroon could be exposed.

**Comment by brh28** [comment]
Yes, ultimately I do need a secure connection, but the cert can be sourced from places other than the client at application start. In this case, I believe it is fetched from a CA, since the connection is established to a voltage server rather than my LND node directly. Setting the cert at runtime seems to override this process and subsequently fails to connect.

**Comment by chill117** [comment]
I've just tested both lnurl-node and lightning-backends-node modules. The `cert` option is not required to create either an instance of the lnurl-node server or the LndBackend. Can you please share the exact error message and related code snippet?

**Comment by brh28** [comment]
It was a versioning issue after all. I thought I was on the latest but was actually on 0.18.1. Upgrading fixed the issue. I appreciate the help even though I'm sorry for dragging you into a dumb mistake on my part.
